menu:
#- {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Research', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/lisha1992'}
- {icon: 'scholar', link: 'https://scholar.google.com/citations?user=PrgZtw4AAAAJ&hl'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/sha-l-248404100/'}

contacts:
- {name: 'Sha Li', title: 'Ph.D. student in Computer Science', lab: '<a href="https://litinghu.github.io/"> Experimental and Virtualized Systems (ELVES) Lab </a>' , department: '<a href="https://cs.vt.edu/"> Department of Computer Science</a>', institution: '<a href="https://vt.edu/">Virginia Tech</a>', institution_address: 'Blacksburg, VA 24060', phone: '(000) 000-0000', email: 'csshali.ls@gmail.com', office: 'Science Building 505', image: 'assets/img/hokie.jpg'}
